---
development:
  cloud_name: dunfca9xv
  api_key: 'CLOUDINARY_KEY'
  api_secret: CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dunfca9xv
  api_key: 'CLOUDINARY_KEY'
  api_secret: CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dunfca9xv
  api_key: 'CLOUDINARY_KEY'
  api_secret: CLOUDINARY_SECRET
  enhance_image_tag: true
  static_image_support: false
